/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here
 } //_CODE_:button1:12356:

 * Do not rename this tab!
 * =========================================================
 */

synchronized public void
win_draw1(PApplet appc, GWinData data) { //_CODE_:window1:318975:
    appc.background(230);
} //_CODE_:window1:318975:

public

void fps_clicked(GCheckbox source, GEvent event) { //_CODE_:fpsOn:628265:
    fpsCounter = source.isSelected();
} //_CODE_:fpsOn:628265:

public

void changeToolAddFluid(
    GImageToggleButton source,
    GEvent event
) { //_CODE_:toolAddFluid:362552:
    changeMouseMode(MouseMode.ADD_FLUID, source);
} //_CODE_:toolAddFluid:362552:

public

void changeToolRemoveFluid(
    GImageToggleButton source,
    GEvent event
) { //_CODE_:toolRemoveFluid:235465:
    changeMouseMode(MouseMode.REMOVE_FLUID, source);
} //_CODE_:toolRemoveFluid:235465:

public

void mouseRadiusChange(
    GSlider source,
    GEvent event
) { //_CODE_:mouseRadiusSlider:923919:
    mouseRadius = source.getValueF();
} //_CODE_:mouseRadiusSlider:923919:

public

void mousePowerChange(
    GSlider source,
    GEvent event
) { //_CODE_:mousePowerSlider:862956:
    mousePower = source.getValueF();
} //_CODE_:mousePowerSlider:862956:

public

void changeToolRepel(
    GImageToggleButton source,
    GEvent event
) { //_CODE_:toolRepel:256301:
    changeMouseMode(MouseMode.REPEL, source);
} //_CODE_:toolRepel:256301:

public

void changeToolAttract(
    GImageToggleButton source,
    GEvent event
) { //_CODE_:toolAttract:504153:
    changeMouseMode(MouseMode.ATTRACT, source);
} //_CODE_:toolAttract:504153:

// Create all the GUI controls.
// autogenerated do not edit
public

void createGUI() {
    G4P.messagesEnabled(false);
    G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
    G4P.setMouseOverEnabled(false);
    surface.setTitle("Sketch Window");
    window1 = GWindow.getWindow(this, "Options", 512, 0, 240, 512, JAVA2D);
    window1.noLoop();
    window1.setActionOnClose(G4P.KEEP_OPEN);
    window1.addDrawHandler(this, "win_draw1");
    fpsOn = new GCheckbox(window1, 110, 10, 120, 20);
    fpsOn.setIconAlign(GAlign.LEFT, GAlign.MIDDLE);
    fpsOn.setText("Fps Counter");
    fpsOn.setOpaque(false);
    fpsOn.addEventHandler(this, "fps_clicked");
    toolAddFluid =
        new GImageToggleButton(window1, 10, 10, "paint-bucket-icon.png", 2, 1);
    toolAddFluid.addEventHandler(this, "changeToolAddFluid");
    toolRemoveFluid =
        new GImageToggleButton(window1, 10, 60, "sponge-icon.png", 2, 1);
    toolRemoveFluid.addEventHandler(this, "changeToolRemoveFluid");
    mouseRadiusSlider = new GSlider(window1, 130, 40, 100, 40, 10.0);
    mouseRadiusSlider.setLimits(10.0, 0.0, 20.0);
    mouseRadiusSlider.setNumberFormat(G4P.DECIMAL, 2);
    mouseRadiusSlider.setOpaque(false);
    mouseRadiusSlider.addEventHandler(this, "mouseRadiusChange");
    mousePowerSlider = new GSlider(window1, 130, 80, 100, 40, 10.0);
    mousePowerSlider.setLimits(15.0, 0.0, 30.0);
    mousePowerSlider.setNumberFormat(G4P.DECIMAL, 2);
    mousePowerSlider.setOpaque(false);
    mousePowerSlider.addEventHandler(this, "mousePowerChange");
    toolRepel =
        new GImageToggleButton(window1, 10, 160, "repel-icon.png", 2, 1);
    toolRepel.addEventHandler(this, "changeToolRepel");
    toolAttract =
        new GImageToggleButton(window1, 10, 110, "attract-icon.png", 2, 1);
    toolAttract.addEventHandler(this, "changeToolAttract");
    window1.loop();
}

// Variable declarations
// autogenerated do not edit
GWindow window1;
GCheckbox fpsOn;
GImageToggleButton toolAddFluid;
GImageToggleButton toolRemoveFluid;
GSlider mouseRadiusSlider;
GSlider mousePowerSlider;
GImageToggleButton toolRepel;
GImageToggleButton toolAttract;
